# table_descriptions.py

TABLE_DESCRIPTIONS = {
    'health': 'Health status of the satellite.',
    'visibility': 'Visibility status of the satellite.',
    'ephUsability': 'Usability of the ephemeris data.',
    'ephSource': 'Source of the ephemeris data.',
    'almUsability': 'Usability of the almanac data.',
    'almSource': 'Source of the almanac data.',
    'anoAopUsability': 'Usability of the anomaly data.',
    'type': 'Type of the parameter.',
    'cno': 'Carrier-to-noise ratio.',
    'elev': 'Elevation angle of the satellite.',
    'azim': 'Azimuth angle of the satellite.',
    'prRes': 'Pseudorange residual.',
    'qualityInd': 'Quality indicator of the signal.',
    'svUsed': 'Indicates if the satellite was used.',
    'diffCorr': 'Differential correction.',
    'smoothed': 'Smoothed measurements.',
    'orbitSource': 'Source of the orbit data.',
    'ephAvail': 'Availability of ephemeris data.',
    'almAvail': 'Availability of almanac data.',
    'prMes': 'Pseudorange measurement.',
    'cpMes': 'Carrier phase measurement.',
    'doMes': 'Doppler measurement.',
    'freqId': 'Frequency identifier.',
    'locktime': 'Lock time of the signal.',
    'prStedv': 'Standard deviation of pseudorange.',
    'cpStedv': 'Standard deviation of carrier phase.',
    'doStedv': 'Standard deviation of Doppler measurement.',
    'prValid': 'Validity of the pseudorange measurement.',
    'cpValid': 'Validity of the carrier phase measurement.',
    'halfCyc': 'Half cycle count for the signal.',
    'subHalfCyc': 'Sub-half cycle count for the signal.',
    'ura': 'User range accuracy.',
    'healthy': 'Health status of the satellite.',
    'ephVal': 'Validity of the ephemeris data.',
    'almVal': 'Validity of the almanac data.',
    'notAvail': 'Indicates if data is not available.',
    'almAge': 'Age of the almanac data.',
    'ephAge': 'Age of the ephemeris data.',
    'mpathIndic': 'Multipath indicator.',
    'dopplerMS': 'Doppler measurement in meters per second.',
    'dopplerHz': 'Doppler measurement in Hertz.',
    'wholeChips': 'Number of whole chips in the signal.',
    'fracChips': 'Fractional part of chips in the signal.',
    'codePhase': 'Code phase measurement.',
    'intCodePhase': 'Integrated code phase measurement.',
    'pseuRangeRMSErr': 'Root mean square error of the pseudorange.',
    'week': 'GPS week number.',
    'Toe': 'Ephemeris reference time.',
    'Toc': 'Clock correction reference time.',
    'IODE1': 'Issue of data ephemeris 1.',
    'IODE2': 'Issue of data ephemeris 2.',
    'IODC': 'Issue of data clock.',
    'IDOT': 'Rate of change of inclination.',
    'Wdot': 'Rate of change of argument of perigee.',
    'Crs': 'Amplitude of sine harmonic correction to the orbit radius.',
    'Crc': 'Amplitude of cosine harmonic correction to the orbit radius.',
    'Cus': 'Amplitude of sine harmonic correction to the argument of latitude.',
    'Cuc': 'Amplitude of cosine harmonic correction to the argument of latitude.',
    'Cis': 'Amplitude of sine harmonic correction to the inclination angle.',
    'Cic': 'Amplitude of cosine harmonic correction to the inclination angle.',
    'dn': 'Rate of change of the mean motion.',
    'i0': 'Inclination angle at reference time.',
    'Tgd': 'Group delay difference.',
    'af2': 'Clock correction parameter 2.',
    'accuracy': 'Accuracy of the ephemeris data.',
    'Toa': 'Almanac reference time.',
    'e': 'Orbital eccentricity.',
    'delta_i': 'Inclination angle correction.',
    'sqrtA': 'Square root of the semi-major axis.',
    'W0': 'Argument of perigee.',
    'w': 'Longitude of ascending node.',
    'M0': 'Mean anomaly at reference time.',
    'af0': 'Clock correction parameter 0.',
    'af1': 'Clock correction parameter 1.',
    'Data_ID': 'Data identifier.'
}
